### ISSUE TITLE
startPingTimer() method crashing

### ISSUE THREAD

**Issue by pankajtirole** [Mastercard/connect-android-sdk#3]
Hi team,

I am getting repeated crash on startPingTimer method. Please help me to fix it. 
I am calling  Connect.finishCurrentActivity() inside onDone, onCancel and onError method.

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
       at com.mastercard.openbanking.connect.Connect$2.run(Connect.java:252)
       at java.util.TimerThread.mainLoop(Timer.java:563)
       at java.util.TimerThread.run(Timer.java:513)

**Comment by adandaboina** [comment]
Regarding your call to Connect.finishCurrentActivity() inside onDone, onCancel, and onError methods, I want to clarify that our SDK handles these actions internally, You shouldn't need to explicitly call Connect.finishCurrentActivity() in any events.

To assist you further and debug the issue effectively, could you please provide us with the following details:

1. Which version of the Connect Android SDK you are using?
2. The Android device model and its Android version where the error is occurring?
3. Is this crash occurring intermittently or every time you launch Connect?
4. Are there any specific actions or scenarios that seem to trigger the crash?

With this information, we'll be better equipped to diagnose and resolve the issue you're facing.

Looking forward to your response.

**Comment by pankajtirole** [comment]
If I will not call  Connect.finishCurrentActivity() then I am start getting crashes and it says "There is already another Connect Activity running" . 
Which version of the Connect Android SDK you are using? - 3.0.2
The Android device model and its Android version where the error is occurring? - Not specific with device
Is this crash occurring intermittently or every time you launch Connect?  - Intermittently
Are there any specific actions or scenarios that seem to trigger the crash? - Not sure
