### ISSUE TITLE
NullPointerException com.mastercard.openbanking.connect.Connect$2.run(Connect.java:247)

### ISSUE THREAD

**Issue by pankajtirole** [Mastercard/connect-android-sdk#6]
Hi Team,

Significant number of users are getting following crash. Can you please help me to resolved it.
          
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
       at com.mastercard.openbanking.connect.Connect$2.run(Connect.java:247)
       at java.util.TimerThread.mainLoop(Timer.java:573)
       at java.util.TimerThread.run(Timer.java:523)

**Comment by pankajtirole** [comment]
Any update on this?

**Comment by adandaboina** [comment]
Hi @pankajtirole , can you give us steps to reproduce?

**Comment by pankajtirole** [comment]
HI @adandaboina, I am unable to reproduce with test account but User those are using actual bank account facing this issue. Please prioritise it and fix it because I can see in crashlytics significant number of users getting it.
